[project]
name = "rtsprice"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["openpyxl", "xlrd", "PyYAML", "Pillow", "paramiko", "requests"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
